### PR TITLE
Bugfix/wotlk classic p2 fixes

### PR DESCRIPTION
**Pull request by Jakobud**

### CODE REVIEW

**Comment by shirsig** [comment]
Thanks a lot, I'm swamped with work at the moment, really appreciate the help.
One thing I noticed, editbox:SetMaxLetters(255) where previously nil was passed - I assume the meaning of nil was unlimited, so this could be too restrictive now in some cases. should probably be the largest number possible by default if unlimited is no longer an option.

**Comment by Jakobud** [comment]
So the number can no longer be `nil` . According to this:

https://wowpedia.fandom.com/wiki/API_EditBox_SetMaxLetters

255 is the max amount allowed.

**Comment by Jakobud** [comment]
Okay I'm not sure if that 255 limit is something that was recently added or not. Definitely a lot of arguments in the API became non-nilable with the WOTLK Phase 2 patch. Probably filtering down from retail.

**Comment by shirsig** [comment]
I was able to get back the unlimited-default behavior by just removing the call altogether. Back when I first implemented it I think there was an error when using the editbox without having set it, but that doesn't seem to be the case anymore.

**Pull request merged**
